// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ognnfanapdotgrmsmwav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nbm5mYW5hcGRvdGdybXNtd2F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3ODcxMzUsImV4cCI6MjA1NjM2MzEzNX0.aLP_uQJVBIYWD1zbeXwNeKLri-_CCtawKLyZ0NlZXdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});